HW02
riazanowa/2024-05-otus-spring-riazanova pull request #2
Opened 2024-07-18 16:41 UTC by riazanowa

Description can be found in README.md

2024-07-21 19:42 UTC, VladimirMagerov requested changes

2024-07-21 19:42 UTC, VladimirMagerov commented on hw02-annotation-config/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +            testResult.applyAnswer(questions.get(i), isAnswerValid);
Нужно поправить соотношение введённого номера ответа и его индекса в коллекции ответов
![image](https://github.com/user-attachments/assets/8b7a1393-8cff-4cfa-b3e7-9f5ea8907771)

2024-07-21 19:42 UTC, VladimirMagerov commented on hw02-annotation-config/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        assertEquals(actualQuestions.size(), 3);
Предлагаю проверить не только размер, но и содержимое.

2024-08-08 14:48 UTC, riazanowa commented on hw02-annotation-config/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +            testResult.applyAnswer(questions.get(i), isAnswerValid);
Поправила

2024-08-09 10:45 UTC, VladimirMagerov approved these changes

2024-08-12 07:42 UTC, merged